### ISSUE TITLE
No such method error

### ISSUE THREAD

**Issue by mancvso** [xitrum-framework/scalive#17]
Hey there! A really nice tool.

Downloaded it today, an attached to an Activator+Play (mixed Java/Scala) in DEV mode with auto-reloading enabled.

```
[Scalive] Open local port 43636 for REPL and completer
[Scalive] REPL connected
[Scalive] Completer connected
[Scalive] Load /home/mancvso/bin/scalive-1.6/scala-library-2.11.8.jar
Exception in thread "scalive.server.Agent-Server" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at scalive.server.Agent$1.run(Agent.java:42)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scalive.Classpath.getScalaVersion(Classpath.java:101)
	at scalive.server.Server.loadDependencyJars(Server.java:50)
	at scalive.server.Server.run(Server.java:35)
	at scalive.server.Agent$1.run(Agent.java:40)
Caused by: java.lang.NoSuchMethodError: scala.util.Properties$.versionNumberString()Ljava/lang/String;
	at scala.util.Properties.versionNumberString(Properties.scala)
	... 8 more
```

By the output of scalalive looks like the agent is running
```
JVM processes:
#pid	Display name
13552	scalive.client.AgentLoader /home/mancvso/bin/scalive-1.6
10845	/home/mancvso/Antarkt/code/panel/activator-launch-1.3.7.jar
```

**Comment by ngocdaothanh** [comment]
As explained at https://github.com/xitrum-framework/scalive#known-issues, currently for now, process with multiple classloaders is not supported (Play dev mode).

You can still use Scalive with Play in production mode.
